services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - tmp-network
  broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: broker
    ports:
      - 9095:9095
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      #listeners
      - KAFKA_LISTENERS=INTER_BROKER://broker:29092, CONTROLLER://broker:29093, LOCAL://0.0.0.0:9095
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTER_BROKER:PLAINTEXT,LOCAL:SASL_PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INTER_BROKER://broker:29092, LOCAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTER_BROKER
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:29093
      #security
      - KAFKA_LISTENER_NAME_LOCAL_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/custom/kafka_jaas_plain_config.conf
    networks:
      - tmp-network
    volumes:
      - ./kafka_conf:/etc/kafka/custom

networks:
  tmp-network:
    driver: bridge
