spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
  flyway:
    locations: "classpath:db/migration"


kafka:
  bootstrap-url: localhost:9095
  group-id: group1